# Algebra Lineal esencial   

El álgebra lineal proporciona las herramientas matemáticas necesarias para representar y manipular los datos de forma matricial. En estadística y ciencia de datos, conceptos como vectores, matrices, productos y transpuestas son fundamentales para expresar modelos estadísticos de manera compacta.

En esta sección se revisarán los conceptos necesarios para comprender posteriormente la formulación matricial de la regresión lineal mediante Mínimos Cuadrados Ordinarios (OLS).  

En esta sección se usará el libro guia: Linear Algebra Done Right, Sheldon Axler. Se presentarán los diferentes conceptos en base a lo que se estará trabajando, pero se dejará el capitulo del libro donde buscar las definiciones generales y más teóricas para el lector.  

Link: https://linear.axler.net/LADR4e.pdf

## Vectores  

Un vector es una colección ordenada de elementos que puede representarse como una fila o una columna. En estadística, un vector puede representar, por ejemplo, las observaciones de una variable.

Un vector columna de $n$ elementos se representa como:

$$
\mathbf{x} =
\begin{bmatrix}
x_1\\
x_2\\
\vdots\\
x_n
\end{bmatrix}
$$

Por ejemplo:

$$
\mathbf{x} =
\begin{bmatrix}
2\\
4\\
6
\end{bmatrix}
$$

Este vector contiene tres elementos, por lo que su dimensión es $3$.

**Leer más en el capitulo 1: Vector Spaces, pag 12.**

In [6]:
import numpy as np

In [7]:
x = np.array([2, 4, 6])

print("Vector:", x)
print("Dimensión:", x.shape)
print("Número de elementos:", len(x))

Vector: [2 4 6]
Dimensión: (3,)
Número de elementos: 3


## Producto punto

El producto punto entre dos vectores de igual dimensión consiste en multiplicar sus elementos correspondientes y sumar los resultados.

Dados:

$$
\mathbf{x} =
\begin{bmatrix}
x_1\\
x_2\\
\vdots\\
x_n
\end{bmatrix}
\qquad
\mathbf{y} =
\begin{bmatrix}
y_1\\
y_2\\
\vdots\\
y_n
\end{bmatrix}
$$

el producto punto se define como:

$$
\mathbf{x}^T\mathbf{y}
=
\sum_{i=1}^{n}x_i y_i
$$

Por ejemplo:

$$
\mathbf{x} =
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix},
\qquad
\mathbf{y} =
\begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
$$

Entonces:

$$
\mathbf{x}^T\mathbf{y}
=
1(4)+2(5)+3(6)
=4+10+18
=32
$$

In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

producto_punto = x @ y

print("Producto punto:", producto_punto)

Producto punto: 32


In [9]:
#también puedes usar esta funcion
producto_punto = np.dot(x, y)

print(producto_punto)

32


El producto punto será fundamental posteriormente porque permite representar combinaciones lineales de variables mediante expresiones matriciales.  

**Leer más en el capítulo 6: Inner Products and Norms, pag 182.**  

## Matrices  

Una matriz es una estructura rectangular organizada en filas y columnas.

Una matriz $X$ con $n$ filas y $p$ columnas se representa como:

$$
X =
\begin{bmatrix}
x_{11} & x_{12} & \cdots & x_{1p}\\
x_{21} & x_{22} & \cdots & x_{2p}\\
\vdots & \vdots & \ddots & \vdots\\
x_{n1} & x_{n2} & \cdots & x_{np}
\end{bmatrix}
$$

Se dice que:

$$
X \in \mathbb{R}^{n\times p}
$$

donde $n$ representa el número de filas y $p$ el número de columnas.

Por ejemplo:

$$
X =
\begin{bmatrix}
1&2\\
3&4\\
5&6
\end{bmatrix}
$$

es una matriz de dimensión $3\times2$.

In [10]:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(X)
print("Dimensiones:", X.shape)
print("Filas:", X.shape[0])
print("Columnas:", X.shape[1])

[[1 2]
 [3 4]
 [5 6]]
Dimensiones: (3, 2)
Filas: 3
Columnas: 2


Las matrices permiten representar conjuntos de datos completos. Por ejemplo, cada fila puede representar una observación y cada columna una variable.  

**Leer más en el capítulo 3: Matrices, pag 69.**

## Transpuesta  

La transpuesta de una matriz se obtiene intercambiando sus filas por sus columnas.

Si:

$$
X =
\begin{bmatrix}
1&2\\
3&4\\
5&6
\end{bmatrix}
$$

entonces:

$$
X^T =
\begin{bmatrix}
1&3&5\\
2&4&6
\end{bmatrix}
$$

Una propiedad importante es:

$$
(X^T)^T=X
$$

In [11]:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

X_transpuesta = X.T

print("Matriz X:")
print(X)

print("\nTranspuesta de X:")
print(X_transpuesta)

Matriz X:
[[1 2]
 [3 4]
 [5 6]]

Transpuesta de X:
[[1 3 5]
 [2 4 6]]


La transpuesta será especialmente importante en expresiones como:

$$
X^TX
$$

que aparecerán posteriormente en la solución matricial de OLS.

## Multiplicación de matrices  

La multiplicación de matrices no consiste en multiplicar elemento por elemento. Cada elemento de la matriz resultante se obtiene mediante el producto punto entre una fila de la primera matriz y una columna de la segunda.

Si:

$$
A\in\mathbb{R}^{m\times n}
$$

y

$$
B\in\mathbb{R}^{n\times p}
$$

entonces el producto:

$$
AB
$$

es posible y produce una matriz de dimensión:

$$
AB\in\mathbb{R}^{m\times p}
$$

Por ejemplo:

$$
A =
\begin{bmatrix}
1&2\\
3&4
\end{bmatrix}
\qquad
B =
\begin{bmatrix}
5&6\\
7&8
\end{bmatrix}
$$

Entonces:

$$
AB =
\begin{bmatrix}
1(5)+2(7)&1(6)+2(8)\\
3(5)+4(7)&3(6)+4(8)
\end{bmatrix}
$$

por lo tanto:

$$
AB =
\begin{bmatrix}
19&22\\
43&50
\end{bmatrix}
$$

**leer más en el capítulo 3D: Matrix Multiplication, pag 72.**


In [12]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

AB = A @ B

print("A:")
print(A)

print("\nB:")
print(B)

print("\nA × B:")
print(AB)

A:
[[1 2]
 [3 4]]

B:
[[5 6]
 [7 8]]

A × B:
[[19 22]
 [43 50]]


En Python, el operador `@` se utiliza para realizar multiplicación matricial.

**Importante:** `A * B` y `A @ B` no representan la misma operación. `*` realiza multiplicación elemento a elemento, mientras que `@` realiza multiplicación matricial.

Ejemplo:

In [13]:
print("Multiplicación elemento a elemento:")
print(A * B)

print("\nMultiplicación matricial:")
print(A @ B)

Multiplicación elemento a elemento:
[[ 5 12]
 [21 32]]

Multiplicación matricial:
[[19 22]
 [43 50]]


### Aplicación a $X^TX$

Si $X$ tiene $n$ observaciones y $p$ variables:

$$
X\in\mathbb{R}^{n\times p}
$$

entonces su transpuesta tiene dimensión:

$$
X^T\in\mathbb{R}^{p\times n}
$$

y:

$$
X^TX\in\mathbb{R}^{p\times p}
$$

Esta matriz será fundamental para obtener la solución de OLS.

In [14]:
X = np.array([
    [1, 2],
    [1, 3],
    [1, 4]
])

print("Dimensión de X:", X.shape)
print("Dimensión de X.T:", X.T.shape)
print("Dimensión de X.T @ X:", (X.T @ X).shape)

print("\nX.T @ X:")
print(X.T @ X)

Dimensión de X: (3, 2)
Dimensión de X.T: (2, 3)
Dimensión de X.T @ X: (2, 2)

X.T @ X:
[[ 3  9]
 [ 9 29]]


## Matriz de diseño $X$

En regresión lineal, los datos pueden representarse mediante una matriz denominada **matriz de diseño**, generalmente representada por $X$.

Consideremos el modelo de regresión lineal simple:

$$
y_i=\beta_0+\beta_1x_i+\epsilon_i
$$

donde:

- $y_i$: variable respuesta.
- $x_i$: variable explicativa.
- $\beta_0$: intercepto.
- $\beta_1$: coeficiente de la variable explicativa.
- $\epsilon_i$: término de error.

Este modelo puede escribirse de forma matricial como:

$$
\mathbf{y}=X\boldsymbol{\beta}+\boldsymbol{\epsilon}
$$

La matriz de diseño contiene una columna de unos para representar el intercepto:

$$
X=
\begin{bmatrix}
1&x_1\\
1&x_2\\
\vdots&\vdots\\
1&x_n
\end{bmatrix}
$$

y el vector de parámetros es:

$$
\boldsymbol{\beta}=
\begin{bmatrix}
\beta_0\\
\beta_1
\end{bmatrix}
$$

Por ejemplo, si tenemos:

$$
x=
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
$$

la matriz de diseño será:

$$
X=
\begin{bmatrix}
1&1\\
1&2\\
1&3
\end{bmatrix}
$$

In [15]:
x = np.array([1, 2, 3])

X = np.column_stack([
    np.ones(len(x)),
    x
])

print("Matriz de diseño X:")
print(X)

print("\nDimensiones de X:")
print(X.shape)

Matriz de diseño X:
[[1. 1.]
 [1. 2.]
 [1. 3.]]

Dimensiones de X:
(3, 2)


La primera columna corresponde al intercepto $\beta_0$ y la segunda contiene los valores de la variable explicativa $x$.


### Conexión con OLS

La representación matricial permite escribir el modelo completo de regresión como:

$$
\mathbf{y}=X\boldsymbol{\beta}+\boldsymbol{\epsilon}
$$

El método de **Mínimos Cuadrados Ordinarios (OLS)** busca los valores de $\boldsymbol{\beta}$ que minimizan la suma de los cuadrados de los residuos:

$$
\min_{\boldsymbol{\beta}}
\|\mathbf{y}-X\boldsymbol{\beta}\|^2
$$

A partir de este problema se obtiene:

$$
X^TX\hat{\boldsymbol{\beta}}=X^T\mathbf{y}
$$

y, cuando $X^TX$ es invertible:

$$
\boxed{
\hat{\boldsymbol{\beta}}
=
(X^TX)^{-1}X^T\mathbf{y}
}
$$

Por esta razón, comprender vectores, transpuestas y multiplicación de matrices es necesario para interpretar la formulación matricial de OLS.

# Matrices definidas positivas  

Las matrices definidas positivas son importantes en estadística porque aparecen de manera natural en expresiones como $X^TX$. Su principal utilidad en este contexto es garantizar ciertas propiedades matemáticas, entre ellas la **invertibilidad**, necesaria para obtener la solución matricial de OLS.

## Matrices simétricas

Una matriz cuadrada $A$ es **simétrica** cuando es igual a su transpuesta:

$$
A=A^T
$$

Por ejemplo:

$$
A=
\begin{bmatrix}
2&1\\
1&3
\end{bmatrix}
$$

Su transpuesta es:

$$
A^T=
\begin{bmatrix}
2&1\\
1&3
\end{bmatrix}
$$

Por lo tanto:

$$
A=A^T
$$

Las matrices simétricas son importantes porque las matrices de la forma $X^TX$ siempre son simétricas:

$$
(X^TX)^T=X^TX
$$


In [ ]:
A = np.array([
    [2, 1],
    [1, 3]
])

print("Matriz A:")
print(A)

print("\nTranspuesta de A:")
print(A.T)

print("\n¿A es simétrica?")
print(np.array_equal(A, A.T))

## ¿Qué significa que una matriz sea definida positiva?

Una matriz cuadrada y simétrica $A$ es **definida positiva** si para cualquier vector $\mathbf{x}\neq0$ se cumple:

$$
\mathbf{x}^T A\mathbf{x}>0
$$

Es decir, al realizar el producto:

$$
\mathbf{x}^T A\mathbf{x}
$$

el resultado siempre es positivo para cualquier vector diferente del vector cero.

Consideremos:

$$
A=
\begin{bmatrix}
2&0\\
0&3
\end{bmatrix}
$$

y:

$$
\mathbf{x}=
\begin{bmatrix}
1\\
2
\end{bmatrix}
$$

Entonces:

$$
\mathbf{x}^TA\mathbf{x}
=
\begin{bmatrix}
1&2
\end{bmatrix}
\begin{bmatrix}
2&0\\
0&3
\end{bmatrix}
\begin{bmatrix}
1\\
2
\end{bmatrix}
$$

El resultado es:

$$
14>0
$$

In [16]:
A = np.array([
    [2, 0],
    [0, 3]
])

x = np.array([1, 2])

resultado = x.T @ A @ x

print("x^T A x =", resultado)

x^T A x = 14


En este caso, el resultado es positivo.

### Comprobar diferentes vectores

Podemos probar diferentes vectores para observar que el resultado continúa siendo positivo:

In [17]:
vectores = [
    np.array([1, 0]),
    np.array([0, 1]),
    np.array([1, 2]),
    np.array([-2, 1])
]

for x in vectores:
    resultado = x.T @ A @ x
    print(f"x = {x},   x^T A x = {resultado}")

x = [1 0],   x^T A x = 2
x = [0 1],   x^T A x = 3
x = [1 2],   x^T A x = 14
x = [-2  1],   x^T A x = 11


Para establecer que una matriz es definida positiva no basta con probar algunos vectores. Una forma práctica de verificarlo para una matriz simétrica es comprobar que **todos sus autovalores sean positivos**.

### Autovalores

In [18]:
autovalores = np.linalg.eigvalsh(A)

print("Autovalores:")
print(autovalores)

print("\n¿Es definida positiva?")
print(np.all(autovalores > 0))

Autovalores:
[2. 3.]

¿Es definida positiva?
True


Si todos los autovalores son mayores que cero, la matriz es definida positiva. A continuación se muestra las diferentes maneras de probar que una matriz es definida positiva o negativa.  

### Theorem

Sea $A \in \mathbb{R}^{n \times n}$ una matriz simétrica con valores propios $\lambda_1, \dots, \lambda_n$ y menores principales $M_1, \dots, M_n$.

* $A$ es definida positiva si y solo si $\lambda_i > 0$ para todo $i = 1, \dots, n$, es decir, si todos sus valores propios son positivos.
* $A$ es definida positiva si y solo si $M_i > 0$ para todo $i = 1, \dots, n$.
* $A$ es definida negativa si y solo si $\lambda_i < 0$ para todo $i = 1, \dots, n$, es decir, si todos sus valores propios son negativos.
* $A$ es definida negativa si y solo si $M_i < 0$ para todo $i$ impar y $M_i > 0$ para todo $i$ par.

## Definida positiva y existencia de la inversa

Una propiedad importante de las matrices definidas positivas es que **son invertibles**.

Si $A$ es definida positiva, entonces todos sus autovalores son mayores que cero:

$$
\lambda_i>0
$$

Por lo tanto, ninguno de sus autovalores es igual a cero y:

$$
\det(A)\neq0
$$

Esto garantiza que existe la matriz inversa:

$$
A^{-1}
$$

Por ejemplo:

$$
A=
\begin{bmatrix}
2&0\\
0&3
\end{bmatrix}
$$

tiene inversa:

$$
A^{-1}=
\begin{bmatrix}
1/2&0\\
0&1/3
\end{bmatrix}
$$


In [19]:
A = np.array([
    [2, 0],
    [0, 3]
])

A_inv = np.linalg.inv(A)

print("Matriz A:")
print(A)

print("\nInversa de A:")
print(A_inv)

Matriz A:
[[2 0]
 [0 3]]

Inversa de A:
[[0.5        0.        ]
 [0.         0.33333333]]


Podemos comprobar que:

$$
AA^{-1}=I
$$

donde $I$ es la matriz identidad.

In [20]:
identidad = A @ A_inv

print(identidad)

[[1. 0.]
 [0. 1.]]



No toda matriz cuadrada es invertible.

Por ejemplo:

$$
B=
\begin{bmatrix}
1&2\\
2&4
\end{bmatrix}
$$

tiene filas y columnas linealmente dependientes. Su determinante es cero:

$$
\det(B)=0
$$

por lo que $B^{-1}$ no existe.

In [21]:
B = np.array([
    [1, 2],
    [2, 4]
])

print("Determinante:", np.linalg.det(B))

Determinante: 0.0


Intentar calcular su inversa genera un problema porque la matriz es singular (borrar el "#" y correr el codigo para ver el error):

In [23]:
#np.linalg.inv(B)

¿Por qué importa para OLS?

En regresión lineal, el modelo puede escribirse como:

$$
\mathbf{y}=X\boldsymbol{\beta}+\boldsymbol{\epsilon}
$$

El estimador de Mínimos Cuadrados Ordinarios es:

$$
\hat{\boldsymbol{\beta}}
=
(X^TX)^{-1}X^T\mathbf{y}
$$

Observemos que aparece la matriz:

$$
X^TX
$$

Esta matriz tiene dos propiedades importantes:

### 1. $X^TX$ es simétrica

Por definición:

$$
(X^TX)^T=X^TX
$$

### 2. $X^TX$ es definida positiva cuando $X$ tiene rango columna completo

Para cualquier vector $\mathbf{z}\neq0$:

$$
\mathbf{z}^TX^TX\mathbf{z}
=
(X\mathbf{z})^T(X\mathbf{z})
=
\|X\mathbf{z}\|^2
$$

Como una norma al cuadrado es positiva cuando $X\mathbf{z}\neq0$:

$$
\mathbf{z}^TX^TX\mathbf{z}>0
$$

cuando las columnas de $X$ son linealmente independientes.

Por lo tanto:

$$
X^TX
\text{ es definida positiva}
$$

y, en consecuencia:

$$
(X^TX)^{-1}
\text{ existe}
$$

Esto permite calcular:

$$
\boxed{
\hat{\boldsymbol{\beta}}
=
(X^TX)^{-1}X^T\mathbf{y}
}
$$

In [25]:
#Ejemplo, condiferemos la matriz de diseño:

X = np.array([
    [1, 1],
    [1, 2],
    [1, 3]
])

y = np.array([2, 3, 5])

print("X:")
print(X)

print("\nX^T X:")
print(X.T @ X)

X:
[[1 1]
 [1 2]
 [1 3]]

X^T X:
[[ 3  6]
 [ 6 14]]


Podemos comprobar que $X^TX$ es simétrica:

In [26]:
XtX = X.T @ X

print("¿X^T X es simétrica?")
print(np.array_equal(XtX, XtX.T))

¿X^T X es simétrica?
True


También podemos comprobar sus autovalores:

In [27]:
autovalores = np.linalg.eigvalsh(XtX)

print("Autovalores de X^T X:")
print(autovalores)

print("\n¿X^T X es definida positiva?")
print(np.all(autovalores > 0))

Autovalores de X^T X:
[ 0.3605897 16.6394103]

¿X^T X es definida positiva?
True


Como los autovalores son positivos, $X^TX$ es definida positiva y, por lo tanto, es invertible.

Finalmente podemos calcular la solución de OLS:

In [28]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y

print("Estimadores de OLS:")
print(beta)

Estimadores de OLS:
[0.33333333 1.5       ]


La relación entre los conceptos estudiados puede resumirse de la siguiente manera:

$$
X
\longrightarrow
X^TX
\longrightarrow
\text{matriz simétrica}
$$

Si las columnas de $X$ son linealmente independientes:

$$
X^TX
\longrightarrow
\text{definida positiva}
$$

y entonces:

$$
X^TX
\longrightarrow
(X^TX)^{-1}\text{ existe}
$$

lo que permite obtener:

$$
\boxed{
\hat{\boldsymbol{\beta}}
=
(X^TX)^{-1}X^T\mathbf{y}
}
$$

**Idea clave:** La definida positividad no se introduce solamente como una propiedad matemática. En OLS, está relacionada con la posibilidad de **invertir $X^TX$** y, por tanto, obtener una solución única para los coeficientes del modelo.